# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

authors = Author.create([{id: 2, name:'Пушкин'},{id: 3, name:'Достоевский'},{id: 4, name:'Чехов'},{id: 5, name:'Гоголь'},{id: 6, name:'Тургенев'},{id: 7, name:'Лермонтов'},{id: 8, name:'Булгаков'},{id: 9, name:'Маяковский'},{id: 10, name:'Ахматова'},{id: 11, name:'Тютчев'}])
books = Book.create([{id: 2,author_id: 2, name: "Капитанская дочка"},{id: 3,author_id: 3, name: "Преступление и наказание"},{id: 4,author_id: 4, name: "Палата №6"},{id: 5,author_id: 5, name: "Мёртвые души"},{id: 6,author_id: 6, name: "Отцы и дети"},{id: 7,author_id: 7, name: "Мцыри"},{id: 8,author_id: 8, name: "Мастер и Маргарита"},{id: 9,author_id: 9, name: "Послушайте!"},{id: 10,author_id: 10, name: "Реквием"},{id: 11,author_id: 11, name: "Стихи"}])
books = Book.create([{id: 111,author_id: 2, name: "Книга 2"},{id: 13,author_id: 2, name: "Книга 3"},{id: 14,author_id: 2, name: "Книга 4"},{id: 15,author_id: 2, name: "Книга 5"},{id: 16,author_id: 2, name: "Книга 6"},{id: 17,author_id: 2, name: "Книга 7"},{id: 18,author_id: 2, name: "Книга 8"},{id: 19,author_id: 2, name: "Книга 9"},{id: 20,author_id: 2, name: "Книга 10"},
{id: 21,author_id: 3, name: "Книга 2"},{id: 23,author_id: 3, name: "Книга 3"},{id: 24,author_id: 3, name: "Книга 4"},{id: 25,author_id: 3, name: "Книга 5"},{id: 26,author_id: 3, name: "Книга 6"},{id: 27,author_id: 3, name: "Книга 7"},{id: 28,author_id: 3, name: "Книга 8"},{id: 29,author_id: 3, name: "Книга 9"},{id: 30,author_id: 3, name: "Книга 10"},
{id: 31,author_id: 4, name: "Книга 2"},{id: 33,author_id: 4, name: "Книга 3"},{id: 34,author_id: 4, name: "Книга 4"},{id: 35,author_id: 4, name: "Книга 5"},{id: 36,author_id: 4, name: "Книга 6"},{id: 37,author_id: 4, name: "Книга 7"},{id: 38,author_id: 4, name: "Книга 8"},{id: 39,author_id: 4, name: "Книга 9"},{id: 40,author_id: 4, name: "Книга 10"},
{id: 41,author_id: 5, name: "Книга 2"},{id: 43,author_id: 5, name: "Книга 3"},{id: 44,author_id: 5, name: "Книга 4"},{id: 45,author_id: 5, name: "Книга 5"},{id: 46,author_id: 5, name: "Книга 6"},{id: 47,author_id: 5, name: "Книга 7"},{id: 48,author_id: 5, name: "Книга 8"},{id: 49,author_id: 5, name: "Книга 9"},{id: 50,author_id: 5, name: "Книга 10"},
{id: 51,author_id: 6, name: "Книга 2"},{id: 53,author_id: 6, name: "Книга 3"},{id: 54,author_id: 6, name: "Книга 4"},{id: 55,author_id: 6, name: "Книга 5"},{id: 56,author_id: 6, name: "Книга 6"},{id: 57,author_id: 6, name: "Книга 7"},{id: 58,author_id: 6, name: "Книга 8"},{id: 59,author_id: 6, name: "Книга 9"},{id: 60,author_id: 6, name: "Книга 10"},
{id: 61,author_id: 7, name: "Книга 2"},{id: 63,author_id: 7, name: "Книга 3"},{id: 64,author_id: 7, name: "Книга 4"},{id: 65,author_id: 7, name: "Книга 5"},{id: 66,author_id: 7, name: "Книга 6"},{id: 67,author_id: 7, name: "Книга 7"},{id: 68,author_id: 7, name: "Книга 8"},{id: 69,author_id: 7, name: "Книга 9"},{id: 70,author_id: 7, name: "Книга 10"},
{id: 71,author_id: 8, name: "Книга 2"},{id: 73,author_id: 8, name: "Книга 3"},{id: 74,author_id: 8, name: "Книга 4"},{id: 75,author_id: 8, name: "Книга 5"},{id: 76,author_id: 8, name: "Книга 6"},{id: 77,author_id: 8, name: "Книга 7"},{id: 78,author_id: 8, name: "Книга 8"},{id: 79,author_id: 8, name: "Книга 9"},{id: 80,author_id: 8, name: "Книга 10"},
{id: 81,author_id: 9, name: "Книга 2"},{id: 83,author_id: 9, name: "Книга 3"},{id: 84,author_id: 9, name: "Книга 4"},{id: 85,author_id: 9, name: "Книга 5"},{id: 86,author_id: 9, name: "Книга 6"},{id: 87,author_id: 9, name: "Книга 7"},{id: 88,author_id: 9, name: "Книга 8"},{id: 89,author_id: 9, name: "Книга 9"},{id: 90,author_id: 9, name: "Книга 10"},
{id: 91,author_id: 10, name: "Книга 2"},{id: 93,author_id: 10, name: "Книга 3"},{id: 94,author_id: 10, name: "Книга 4"},{id: 95,author_id: 10, name: "Книга 5"},{id: 96,author_id: 10, name: "Книга 6"},{id: 97,author_id: 10, name: "Книга 7"},{id: 98,author_id: 10, name: "Книга 8"},{id: 99,author_id: 10, name: "Книга 9"},{id: 100,author_id: 10, name: "Книга 10"},
{id: 101,author_id: 11, name: "Книга 2"},{id: 103,author_id: 11, name: "Книга 3"},{id: 104,author_id: 11, name: "Книга 4"},{id: 105,author_id: 11, name: "Книга 5"},{id: 106,author_id: 11, name: "Книга 6"},{id: 107,author_id: 11, name: "Книга 7"},{id: 108,author_id: 11, name: "Книга 8"},{id: 109,author_id: 11, name: "Книга 9"},{id: 110,author_id: 11, name: "Книга 10"},
    ])
